[package]
name = "parity-secretstore-primitives"
version = "1.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
link = { package = "parity-secretstore-primitives", git = "https://github.com/svyatonik/secretstore-primitives.git", branch = "dev" }