[workspace]
members = [
	"blockchain-service",
	"ethereum-service",
	"http-service",
	"key-server",
	"primitives",
	"substrate-service",
	"bin/http",
	"bin/standalone",
	"bin/substrate",
	"bin/util",
]
