[package]
name = "parity-secretstore-util"
version = "1.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[[bin]]
name = "secretstore-util"
path = "src/main.rs"

[dependencies]
clap = { version = "2", features = ["yaml"] }
parity-crypto = { version = "0.4.2", features = ["publickey"] }

