[package]
description = "Parity Secret Store Key Server"
name = "parity-secretstore-key-server"
version = "1.0.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
byteorder = "1.0"
ethabi = "9.0.1"
ethabi-contract = "9.0.0"
ethabi-derive = "9.0.1"
ethereum-types = "0.8.0"
futures = "0.1"
futures03 = { package = "futures", version = "0.3", features = ["compat", "thread-pool"] }
hyper = { version = "0.12", default-features = false }
keccak-hash = "0.4.0"
kvdb = "0.4.0"
kvdb-rocksdb = "0.5.0"
lazy_static = "1.0"
libsecp256k1 = { version = "0.3.5", default-features = false }
log = "0.4"
parity-bytes = "0.1"
parity-crypto = { version = "0.5.0", features = ["publickey"] }
parking_lot = "0.10"
percent-encoding = "2.1.0"
rustc-hex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak = "1.4"
tokio = "0.1.22"
tokio-io = "0.1"
tokio-service = "0.1"
url = "2.1.0"
jsonrpc-server-utils = "14.0.3"
primitives = { package = "parity-secretstore-primitives", path = "../primitives" }

[dev-dependencies]
env_logger = "0.5"
tempdir = "0.3"
kvdb-rocksdb = "0.5.0"
parity-runtime = { version = "0.1.1", features = ["test-helpers"] }
