[package]
name = "parity-secretstore-substrate"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ansi_term = "0.9"
codec = { package = "parity-scale-codec", version = "1.0" }
env_logger = "0.7"
futures = "0.3"
hex = "0.4"
#jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee.git", features = ["ws"] }
jsonrpsee = { path = "/home/svyatonik/dev/jsonrpsee", features = ["ws"] }
log = "0.4"
parity-crypto = "0.4"
parking_lot = "0.9"
parity-secretstore-substrate-service = { path = "../../substrate-service" }
parity-secretstore-key-server = { path = "../../key-server" }
parity-secretstore-primitives = { path = "../../primitives" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.1"

[dependencies.sp-core]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "sp-core"

[dependencies.sp-runtime]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "sp-runtime"

[dependencies.frame-system]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "frame-system"
features = ["std"]

[dependencies.pallet-transaction-payment]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "pallet-transaction-payment"
features = ["std"]

[dependencies.node-runtime]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "node-runtime"

[dependencies.node-primitives]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "node-primitives"

[dependencies.ss-primitives]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "ss-primitives"

[dependencies.substrate-secret-store-runtime]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "substrate-secret-store-runtime"

[dependencies.sp-keyring]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "sp-keyring"

[dependencies.sp-version]
git = "https://github.com/svyatonik/substrate"
rev = "c7a94d9d2100e9db8034f289e3ba038c1f84a66d"
package = "sp-version"